### ISSUE TITLE
slow re-compile for the demobrowser

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qxl.demobrowser#6]
When editing a single app while running `qx serve` it takes 4 minutes to 'recompile'.
This makes it very hard to edit in tree when one is used to fast compiler turnaround times.

**Comment by hkollmann** [comment]
With https://github.com/qooxdoo/qxl.demobrowser/commit/691a865f01424f01a3b38934726bc10586b77056 only those applications are recompiled which are not compiled before.
