### ISSUE TITLE
Table Remote Model date fetch returns 404

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qxl.demobrowser#9]
A 404 is observed in the console when trying to load the remote model demo. It's trying to reach [https://qooxdoo.org/qxl.demobrowser/demobrowser/demo/table/demobrowser/backend/remote_table.php?method=checkphp](url)

**Comment by cboulanger** [comment]
The previous "fake backend" was based on PHP, which doesn't work on GitHub Pages where the current demobrowser is hosted. It needs to be replaced with static data.

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qxl.demobrowser/commit/1fe0c87d00b4222778d98c4e4dc89fd8e751e541
